services:
  traefik:
    image: docker.io/traefik:v3.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backend/docker/local/traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - nextgen_local_nw
    command:
      - --providers.docker

  api: &api
    build:
      context: .
      dockerfile: ./backend/docker/local/fastapi/Dockerfile
    volumes:
      - .:/src
      - ./backend/app/logs:/src/backend/app/logs

    ports:
      - "8000:8000"

    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
    command: /start.sh
    networks:
      - nextgen_local_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routes.api.rule=Hoasr(`api.localhost`)"
      - "traefik.http.routers.api.services=api-services"
      - "traefik.http.services.api-services.loadbalancer.server.port=8000"

  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - nextgen_mailpit_data:/data
    environment:
      MP_MAX_MESSAGE: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCPEPT_ANY: 1
    networks:
      - nextgen_local_nw

  postgres:
    build:
      context: .
      dockerfile: ./backend/docker/local/postgres/Dockerfile
    ports:
      - "5433:5433"
    volumes:
      - nextgen_local_db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - nextgen_local_nw
  
networks:
  nextgen_local_nw:
    external: true

volumes:
  nextgen_local_db:
  nextgen_mailpit_data:

