"""add_bank_account_table

Revision ID: 73cd74d9531d
Revises: 61f1cbd7336d
Create Date: 2025-11-02 02:03:23.503546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73cd74d9531d'
down_revision: Union[str, None] = '61f1cbd7336d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankaccount',
    sa.Column('account_type', sa.Enum('Current', 'Savings', 'FixedDeposit', 'Business', name='accounttypeenum'), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'KES', name='accountcurrencyenum'), nullable=False),
    sa.Column('account_status', sa.Enum('Active', 'Inactive', 'Pending', 'Closed', 'Frozen', name='accountstatusenum'), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('kyc_submitted', sa.Boolean(), nullable=False),
    sa.Column('kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_verified_by', sa.Uuid(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('kyc_verified_on', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankaccount_account_number'), 'bankaccount', ['account_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bankaccount_account_number'), table_name='bankaccount')
    op.drop_table('bankaccount')
    # ### end Alembic commands ###