"""fix_bank_account_kyc_field

Revision ID: 87c1b0311793
Revises: 73cd74d9531d
Create Date: 2025-11-02 03:49:49.037244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87c1b0311793'
down_revision: Union[str, None] = '73cd74d9531d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bankaccount', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.alter_column('bankaccount', 'kyc_verified_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'bankaccount', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bankaccount', type_='foreignkey')
    op.alter_column('bankaccount', 'kyc_verified_on',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('bankaccount', 'user_id')
    # ### end Alembic commands ###