"""add_transaction_table

Revision ID: be87d8d99453
Revises: e023cb783416
Create Date: 2025-11-02 13:21:50.800088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be87d8d99453'
down_revision: Union[str, None] = 'e023cb783416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotencykey',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotencykey_key'), 'idempotencykey', ['key'], unique=True)
    op.create_table('transaction',
    sa.Column('amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_type', sa.Enum('Deposit', 'Withdrawal', 'Transfer', 'Reversal', 'Fee_charged', 'Loan_Disbursement', 'Loan_Repayment', 'Interest_Credited', name='transactiontypeenum'), nullable=False),
    sa.Column('transaction_category', sa.Enum('Credit', 'Debit', name='transactioncategoryenum'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Completed', 'Failed', 'Reversed', 'cancelled', name='transactionstatusenum'), nullable=False),
    sa.Column('balance_before', sa.Numeric(scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(scale=2), nullable=False),
    sa.Column('failed_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_account_id', sa.Uuid(), nullable=True),
    sa.Column('receiver_account_id', sa.Uuid(), nullable=True),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('receiver_id', sa.Uuid(), nullable=True),
    sa.Column('processed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('transaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['processed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['bankaccount.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['bankaccount.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_reference'), 'transaction', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_reference'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_idempotencykey_key'), table_name='idempotencykey')
    op.drop_table('idempotencykey')
    # ### end Alembic commands ###