"""add_idempotency_key_table

Revision ID: dd902c3c05b9
Revises: a5cc56ce2757
Create Date: 2025-11-09 05:05:00.044224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd902c3c05b9'
down_revision: Union[str, None] = 'a5cc56ce2757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###